### ISSUE TITLE
Kafka Connect behind Proxy

### ISSUE THREAD

**Issue by msiddiqi** [datamountaineer/docs#31]
Hi, 

We use FTP proxy to access external FTP site. How can we configure proxy details and credentials in Kafka Connect FTP connector?

EDIT: I couldn't find any details here: http://docs.datamountaineer.com/en/latest/ftp-source.html

Thanks,
Muhammad

**Comment by andrewstevenson** [comment]
@msiddiqi The connection is set to passive mode so should work by setting the address and password, although not tested, otherwise it might need a pull request (we welcome contributions) to set  

`System.getProperties().put( "socksProxyPort", "9090"); 
System.getProperties().put( "socksProxyHost" ,"xxx");`

Can you tell me your use case?

Also this is the docs issues, better post future issues on the stream reactor repo.

**Comment by msiddiqi** [comment]
Hi andrewstevenson,

We are behind a corporate proxy and need to connect to an external FTP source. 

When I run the following, I do see that the connector is loaded fine:
curl localhost:8083/connector-plugins
{"class":"com.datamountaineer.streamreactor.connect.ftp.FtpSourceConnector","type":"source","version":"null"}

But running the following returns empty result:
curl localhost:8083/connector-plugins

Thanks,
Muhammad

**Comment by andrewstevenson** [comment]
@msiddiqi ? The second curl is the same as the first? Also have you tried Landoops Kafka Connect UI tool? We have http://kafka-lenses.io coming out soon.

Additionally we have a cli so you don't need to curl https://github.com/datamountaineer/kafka-connect-tools

**Comment by msiddiqi** [comment]
Sorry, I fixed the curl.

**Comment by andrewstevenson** [comment]
@msiddiqi How did you get on?

**Comment by msiddiqi** [comment]
I even tried adding -Dftp proxy settings in kafka-runner but still the same issue.

**Comment by andrewstevenson** [comment]
@msiddiqi I've raised an issue on the stream reactor. this is the docs repo.
